# Generated by Django 5.0.10 on 2024-12-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('champ', 'Champ'), ('lead', 'Lead'), ('client', 'Client')], default='lead', max_length=20),
        ),
    ]
