# Generated by Django 5.1.2 on 2024-10-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('primary', 'primary'), ('warning', 'warning'), ('danger', 'danger')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='filestatus',
            unique_together={('customer', 'file', 'date')},
        ),
    ]
